# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftMVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftMVVM
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'RxSwiftMVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftMVVMUITests' do
    # Pods for testing
  end

end
